### ISSUE TITLE
[BUG] Getting "Error (1): Invalid entry header" when running the scanner

### ISSUE THREAD

**Issue by yyen-sfdc** [forcedotcom/sfdx-scanner#1544]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Getting "Error (1): Invalid entry header" when running the scanner from my Terminal command line.

### Steps To Reproduce

Ran following command in Terminal on my Mac:

sfdx scanner:run -t <targetdir> -f json -o <outputfile>, where <targetdir> points to my SFDX project folder /force-app/main/default/staticresources

And I'm getting the following error:

Error (1): Invalid entry header

I am running 3.26.0 of the scanner.  I get the same error running 4.3.0 and 4.3.2 of the scanner.  I was able to get the scanner to work with a different project using 3.26.0.

### Expected Behavior

Expected behavior is that the scanner successfully runs with output.

It would be helpful if the error message gave more details as to which file generated the error.

### Operating System

MacOS Sonoma 14.5

### Salesforce CLI Version

@salesforce/cli/2.48.6 darwin-x64 node-v20.14.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 3.26.0 (3.26.0)

### Urgency

High

**Comment by jfeingold35** [comment]
@yyen-sfdc , can you please include the values you're using for `-t` and `-o`?

**Comment by jfeingold35** [comment]
@yyen-sfdc , also, can you try upgrading to v4.x and let me know if you still experience this?

**Comment by yyen-sfdc** [comment]
sfdx scanner:run -t /MyProject/force-app/main/default/staticresources -f json -o ScannerOutput.json

I have tried the scanner with v4.3.0 and v4.3.2 but both give me the below error:
Error (1): RetireJS: env: node: No such file or directory

**Comment by jfeingold35** [comment]
@yyen-sfdc , can you run `node -v` from your command line and let me know what output you get?

**Comment by yyen-sfdc** [comment]
@jfeingold35

zsh: command not found: node

**Comment by jfeingold35** [comment]
@yyen-sfdc , [install node](https://nodejs.org/en/download/package-manager), and that should fix it.

**Comment by yyen-sfdc** [comment]
Thanks @jfeingold35 I installed node and installed scanner v4.3.0 and v4.3.2, both returned with the following error.  v3.26.0 still works.  But on another repo, it still fails with the "Error (1): Invalid entry header" on the staticresources folder.

/Users/yyen/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:253
            throw new core_1.SfError(message);
            ^

SfError: Cannot read properties of undefined (reading 'map')
    at RetireJsEngine.processOutput (/Users/yyen/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:253:19)
    at ChildProcess.<anonymous> (/Users/yyen/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:176:30)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}

Node.js v20.14.0

**Comment by jfeingold35** [comment]
@yyen-sfdc , okay, the "cannot read properties of undefined" error tells me _what's_ happening, but I can't figure out how or why, and I still can't reproduce locally. And since both that error and the "Invalid entry header" error are only reproducible on specific repos, I'm confident that it's some weird property of your code.
Can you please provide a link to one of the repos, so I can run against that and debug? Alternatively, I could send you a tarball with a custom version of the scanner that might provide more detailed information.

**Comment by yyen-sfdc** [comment]
Hi @jfeingold35 I am working on pinpointing exactly which file is generating the Invalid entry header, but I still don't understand why v4.3.0 and v4.3.2 don't work for me.  For now, I'm going to proceed with v3.26.0.

**Comment by jfeingold35** [comment]
@yyen-sfdc , could you please double-check that v4.3.0 and v4.3.2 are broken in the same way? If v4.3.0 is broken, and v3.26.0 isn't, then that narrows down the possible causes very significantly.

**Comment by yyen-sfdc** [comment]
@jfeingold35 Yes, v4.3.0 and v.4.3.2 generated the same error message.

/Users/yyen/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:253
throw new core_1.SfError(message);
^

SfError: Cannot read properties of undefined (reading 'map')
at RetireJsEngine.processOutput (/Users/yyen/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:253:19)
at ChildProcess. (/Users/yyen/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:176:30)
at ChildProcess.emit (node:events:519:28)
at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
cause: undefined,
actions: undefined,
exitCode: 1
}

Node.js v20.14.0

**Comment by jfeingold35** [comment]
@yyen-sfdc , okay, that narrows things down somewhat. The problem is likely some kind of behavioral difference between the versions of RetireJS used by v3.x and v4.x that we weren't aware of. As mentioned above, the best options here are either you can send me the repo information so I can try to debug this myself, or I could send you a custom version of the scanner that might make it a little easier for you to debug.

**Comment by jfeingold35** [comment]
@yyen-sfdc , as suspected, the "Cannot read properties of undefined" error is being caused by a behavioral difference between versions of RetireJS. I believe that this difference is a bug, and have logged [this Issue](https://github.com/RetireJS/retire.js/issues/443) with the RetireJS team. I'll keep an eye on it, and add updates as and when they become available.

**Comment by jfeingold35** [comment]
@yyen-sfdc , the RetireJS team has closed the issue and published a new patch with the fix for the `cannot read properties of undefined` problem, and I've verified that their fix works. Our next Code Analyzer release, v4.4.0, is currently scheduled for July 30, and the fix should go out then.
Have you made any progress in identifying which file is causing the `Invalid entry header` error?

**Comment by yyen-sfdc** [comment]
Thanks for the update @jfeingold35.

I wasn't able to identify which file is causing the Invalid entry header error.  I wrote a script to execute scan on every file and directory within the staticresources directory, which ran without errors.  But when I run the scan on the staticresources directory, that's when I get the error.

**Comment by jfeingold35** [comment]
Update for posterity's sake: Working with @yyen-sfdc , we determined that the problem here is an insufficient contextualization of errors thrown when our RetireJS wrapper can't unzip a ZIP. This will be added as a bug.

**Comment by jfeingold35** [comment]
@yyen-sfdc , I've merged a Pull Request that will cause these errors to be wrapped in a prefix that clarifies where they're coming from. That will go out with the upcoming 4.3.0 release (currently scheduled for July 30).
